# Generated by Django 4.1.2 on 2022-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='idimage',
            field=models.ImageField(default='samuele-bertoli-C0gX9PFh07Q-unsplash.jpg', upload_to='id_photos'),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='user_image',
            field=models.ImageField(default='samuele-bertoli-C0gX9PFh07Q-unsplash.jpg', upload_to='user_images'),
        ),
    ]
