# Generated by Django 4.1.2 on 2022-10-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
