# Generated by Django 4.1.2 on 2022-11-03 16:05

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
