# Generated by Django 4.1.2 on 2022-11-04 09:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=tinymce.models.HTMLField(default='<p>Hello World</p>'),
        ),
    ]
