# Generated by Django 4.1.2 on 2022-11-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_product_slug_alter_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
