# Generated by Django 4.1.2 on 2022-11-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
    ]
