# Generated by Django 4.1.2 on 2022-11-04 10:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=tinymce.models.HTMLField(default='<p>Hello World</p>'),
        ),
    ]
