# Generated by Django 4.1.2 on 2022-11-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
