# Generated by Django 4.1.2 on 2022-11-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
