# Generated by Django 4.1.2 on 2022-11-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_productimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
    ]
