# Generated by Django 4.1.2 on 2022-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_remove_photo_description_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
