# Generated by Django 4.1.2 on 2022-11-06 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='photo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
