# Generated by Django 4.1.2 on 2022-11-06 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_remove_bid_timestamp_photo_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='photo',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
