# Generated by Django 4.1.2 on 2022-11-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_remove_photo_category_remove_photo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
