# Generated by Django 4.1.2 on 2022-11-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_product_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='products',
            new_name='product',
        ),
    ]
