# Generated by Django 4.1.2 on 2022-11-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_alter_bid_options_remove_bid_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='product_bided',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.product'),
        ),
    ]
