# Generated by Django 4.1.2 on 2022-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_alter_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.CharField(max_length=200),
        ),
    ]
