# Generated by Django 4.1.2 on 2022-11-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_alter_bid_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='product_bided',
            new_name='product',
        ),
    ]
